#!/usr/bin/env python3
"""
raceGPS — Cross-Platform UE5 Build Script
Replaces build-akron.bat with auto-detection and Python orchestration.
"""

import argparse
import json
import os
import platform
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def find_ue5_engine() -> str:
    """Auto-detect UE5 install path."""
    system = platform.system()
    candidates = []

    if system == 'Windows':
        # Check registry and common paths
        candidates.extend([
            r'C:\Program Files\Epic Games\UE_5.5',
            r'C:\Program Files\Epic Games\UE_5.4',
            r'C:\Program Files\Epic Games\UE_5.3',
            r'D:\Epic Games\UE_5.5',
            r'D:\UE_5.5',
        ])
        try:
            import winreg
            with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r'SOFTWARE\EpicGames\Unreal Engine\5.5') as key:
                path, _ = winreg.QueryValueEx(key, 'InstalledDirectory')
                if path:
                    candidates.insert(0, path)
        except Exception:
            pass
    elif system == 'Darwin':
        candidates.extend([
            '/Users/Shared/Epic Games/UE_5.5',
            '/Applications/Epic Games/UE_5.5',
        ])
    else:
        candidates.extend([
            os.path.expanduser('~/UnrealEngine_5.5'),
            '/opt/UnrealEngine_5.5',
        ])

    for c in candidates:
        build_tool = os.path.join(c, 'Engine', 'Build', 'BatchFiles', 'RunUAT.bat' if system == 'Windows' else 'RunUAT.sh')
        if os.path.exists(build_tool):
            return c

    return None


def generate_version_header(project_dir: str) -> str:
    """Generate Version.h with git commit and timestamp."""
    try:
        commit = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], cwd=project_dir, text=True).strip()
    except Exception:
        commit = 'unknown'

    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')

    header = f'''// Auto-generated by scripts/build.py
#pragma once
#define RACEGPS_VERSION_COMMIT TEXT("{commit}")
#define RACEGPS_VERSION_DATE TEXT("{timestamp}")
#define RACEGPS_VERSION_STRING TEXT("v0.1.0-beta ({commit})")
'''

    version_dir = os.path.join(project_dir, 'Source', 'raceGPSAkronBeta')
    os.makedirs(version_dir, exist_ok=True)
    version_path = os.path.join(version_dir, 'Version.h')
    with open(version_path, 'w') as f:
        f.write(header)
    return version_path


def build_project(engine_path: str, project_file: str, config: str, target: str) -> bool:
    """Run UAT BuildCookRun."""
    system = platform.system()
    uat = os.path.join(engine_path, 'Engine', 'Build', 'BatchFiles', 'RunUAT.bat' if system == 'Windows' else 'RunUAT.sh')

    if not os.path.exists(uat):
        print(f'ERROR: UAT not found at {uat}', file=sys.stderr)
        return False

    cmd = [
        uat,
        'BuildCookRun',
        f'-project={project_file}',
        f'-target={target}',
        f'-clientconfig={config}',
        f'-serverconfig={config}',
        '-platform=Win64' if system == 'Windows' else '-platform=Linux',
        '-noP4',
        '-build',
        '-cook',
        '-stage',
        '-pak',
        '-archive',
        f'-archivedirectory={os.path.join(os.path.dirname(project_file), "Build")}'
    ]

    print(f'Running: {" ".join(cmd)}')
    result = subprocess.run(cmd)
    return result.returncode == 0


def main():
    parser = argparse.ArgumentParser(description='raceGPS UE5 Build Script')
    parser.add_argument('--config', '-c', default='Development', choices=['Development', 'Shipping', 'Test'], help='Build configuration')
    parser.add_argument('--target', '-t', default='raceGPSAkronBeta', help='Target name')
    parser.add_argument('--engine', '-e', help='UE5 engine path (auto-detected if omitted)')
    parser.add_argument('--project', '-p', default=None, help='.uproject file path')
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.join(script_dir, '..', 'apps', 'unreal-akron-beta')

    if args.project:
        project_file = args.project
    else:
        project_file = os.path.join(project_dir, 'raceGPSAkronBeta.uproject')

    if not os.path.exists(project_file):
        print(f'ERROR: Project file not found: {project_file}', file=sys.stderr)
        sys.exit(1)

    engine = args.engine or find_ue5_engine()
    if not engine:
        print('ERROR: Could not auto-detect UE5 engine. Please specify with --engine', file=sys.stderr)
        sys.exit(1)

    print(f'Engine: {engine}')
    print(f'Project: {project_file}')

    version_path = generate_version_header(project_dir)
    print(f'Generated version header: {version_path}')

    success = build_project(engine, project_file, args.config, args.target)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
